config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  devise_for :users
  resources :users
  resources :events do
    resources :attendances
    resources :charges
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  after_create :send_confirmation_attendance
  belongs_to :event
  belongs_to :attendee, class_name: "User"

  def send_confirmation_attendance
    UserMailer.confirm_attendee(self).deliver_now
  end
end

app/models/event.rb
  class Event < ApplicationRecord
    validates :start_date, presence: true
    validate :is_not_past

    validates :duration, presence: true
    validate :multiple_of_five

    validates :title, presence: true, length: 5..140
    validates :description, presence: true, length: 20..1000
    validates :price, presence: true, inclusion: {in: 0..1000}
    validates :location, presence: true


    has_many :attendances
    has_many :attendees, through: :attendances, class_name: "User"
    belongs_to :admin, class_name: "User"

    def is_not_past
      errors.add(:start_date, "can't be in the past") if start_date < Date.today
    end

    def multiple_of_five
      duration % 5 == 0
    end

    def is_free?
      self.price == 0
    end
  end

app/models/user.rb
  class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
    after_create :send_welcome

    has_many :events, foreign_key: "admin_id", class_name: "Event"
    has_many :attendances, foreign_key: "attendee_id", class_name: "Attendance"

    def send_welcome
      UserMailer.welcome_email(self).deliver_now
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :is_admin?, only: [:index]

  def index
    @event = Event.find(params[:event_id])
    @all_attendances = Attendance.where(event_id: @event.id)
  end

  def create
    @amount = (Event.find(params[:event_id]).price)*100
    @event = Event.find(params[:event_id])

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'eur',
    })

    Attendance.create!(attendee_id: current_user.id, event_id: @event.id, stripe_customer_id: customer.id)

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_event_attendance_path(@event.id)
  end


  def show
    @event = Event.find(params[:event_id])
    @all_attendances = Attendance.all

  end

  def edit
  end

  def update
  end

  def destroy
  end

  def is_admin?
    current_user == Event.find(params[:id]).admin_id
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @event = Event.find(params[:event_id])
  end

  def create
    # Amount in cents
    @event = Event.find(params[:event_id])

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @event.price*100,
      description: 'Rails Stripe customer',
      currency: 'eur',
    })
    # if payment succeed, we create a new intance of Attendance with the customer id. 
    Attendance.create!(event_id: @event.id, attendee_id: current_user.id, stripe_customer_id: customer.id)
    

  rescue Stripe::CardError => e
    flash[:error] = e.message

  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create]
  before_action :is_admin?, only: [:edit, :update, :destroy]

  def index
    @all_events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new

  end

  def create
    @event = Event.create!(start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], price: params[:price], location: params[:location], admin_id: current_user.id)
    if @event.save
      redirect_to event_path(@event.id)
    else
      flash.now[:danger] = 'You must fill out all required fields'
      render 'new'
    end
  end


  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], price: params[:price], location: params[:location], admin_id: current_user.id)
      redirect_to event_path(@event.id)
    else
      flash.now[:danger] = 'You must fill out all required fields'
      render 'new'
    end
  end

  def destroy
    Event.find(params[:id]).destroy
    redirect_to root_path

  end

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_user_session_path
    end
  end

  def is_admin?
    current_user == Event.find(params[:id]).admin_id
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, except: [:new, :create]
  before_action :not_your_profile, except: [:new, :create]

  def new
  end

  def show
    @user = User.find(params[:id])

  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_user_session_path
    end
  end

  def not_your_profile
      redirect_to root_path if current_user != User.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def not_admin_nor_attending
    current_user != @event.admin && !Attendance.where(attendee_id: current_user.id, event_id: @event.id).exists?
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/create.html.erb
<h1>Attendances#create</h1>
<p>Find me in app/views/attendances/create.html.erb</p>

app/views/attendances/destroy.html.erb
<h1>Attendances#destroy</h1>
<p>Find me in app/views/attendances/destroy.html.erb</p>

app/views/attendances/edit.html.erb
<h1>Attendances#edit</h1>
<p>Find me in app/views/attendances/edit.html.erb</p>

app/views/attendances/index.html.erb
<h1>Your event : <%=@event.title%> </h1>

<h2>List of attendees</h2>

<table class="table">
	<thead>
		<tr>
			<th scope="col">#</th>
			<th scope="col">First Name</th>
			<th scope="col">Last Name</th>
			<th scope="col">Email</th>
		</tr>
	</thead>
	<tbody>
		<% i=1 %>
		<% @all_attendances.each do |participation| %>
		<tr>
			<th scope="row"><%=i%></th>
			<td><%=participation.attendee.first_name%></td> 
			<td><%=participation.attendee.last_name%></td> 
			<td><%=participation.attendee.email%></td> 
			<%i+=1%>
		</tr>
		<%end%>
	</tbody>
</table>

<% if current_user == @event.admin %>
<div class="text-center">
	<%= link_to "Edit event", edit_event_path(@event.id), class: "btn btn-outline-info" %>

	<%= link_to "Delete event", event_path(@event.id), method: :delete, class: "btn btn-outline-danger" %>
</div>

<%end%>

app/views/attendances/new.html.erb
<!DOCTYPE html>
<html>
<head></head>
<body>

  <%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
    <% end %>
    <label class="amount">
      <span>Amount: <%= params[:amount] %>€</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-description="A month's subscription"
  data-amount="<%= params[:amount] %>"
  data-locale="auto"></script>

  <% end %>
  <%= yield %>
</body>
</html>

app/views/attendances/show.html.erb
<h1>Attendances#show</h1>
<p>Find me in app/views/attendances/show.html.erb</p>

app/views/attendances/update.html.erb
<h1>Attendances#update</h1>
<p>Find me in app/views/attendances/update.html.erb</p>

app/views/charges/create.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <h2>Thanks, you paid <strong><%= @event.price%>€</strong>!</h2>
	<%= link_to "Come back to the event page", event_path(@event)%>
    <%= yield %>
  </body>
</html>

app/views/charges/new.html.erb
<%= form_tag event_charges_path do %>
<article>
  <% if flash[:error].present? %>
  <div id="error_explanation">
    <p><%= flash[:error] %></p>
  </div>
  <% end %>
  <label class="amount">
    <span>Amount: <%=@event.price%> </span>
  </label>
</article>

<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
data-description="A month's subscription"
data-amount="<%=@event.price*100%>"
data-locale="auto"></script>
<% end %>

app/views/events/create.html.erb
<h1>Event#create</h1>
<p>Find me in app/views/event/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Event#destroy</h1>
<p>Find me in app/views/event/destroy.html.erb</p>

app/views/events/edit.html.erb
<div class="ml-4 mt-5">
  <!-- FLASH : error in case the user doesn't fill the form correctly -->
  <% if flash[:danger] %>
  <div class='alert alert-danger' role='alert'>
    <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
      <span class="close-button" aria-hidden='true'>&times</span>
    </button>
  </div>
  <% end %>

<h1>Edit your event : <%=@event.title%></h1>

  <%= form_tag url_for(action: 'update'), method: "put" do %>

       <%= label_tag 'Title' %><br/>
       <%= text_field_tag 'title'%>
       <br /> <br />

       <%= label_tag 'Description (minimum 20 caracters)' %><br/>
       <%= text_area_tag 'description'%>
       <br/> <br />

       <%= label_tag 'Start Date (yyyy-mm-dd hh:mm:ss)' %><br/>
       <%= text_area_tag 'start_date'%>
       <br/> <br />

       <%= label_tag 'Duration' %><br/>
       <%= text_area_tag 'duration'%>
       <br/> <br />

       <%= label_tag 'Location' %><br/>
       <%= text_area_tag 'location'%>
       <br/> <br />

       <%= label_tag 'Price' %><br/>
       <%= text_area_tag 'price'%>
       <br/> <br />

       <%= submit_tag "Edit Post" %>
     <% end %>

app/views/events/index.html.erb
<div class="jumbotron">
  <h1 class="display-4 text-white font-weight-bold text-center">Welcome to EventBro !</h1>
</div>


<div class="container">
  <div class="row">
    <% @all_events.each do |event| %>
    <div class="col-sm-4 mb-4">
      <div class="list-group">
        <a href="<%=event_path(event.id)%>" class="list-group-item list-group-item-action">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">N°<%=event.id%> by <%= event.admin.first_name %></h5>
          </div>
          <p class="mb-1"><%= event.title %></p>
        </a>
      </div>
      <div class="text-center mt-1">
        <a href="<%= event_path(event.id) %>" class="btn btn-outline-info text-center">Info</a>
        <a href="" class="btn btn-outline-success text-center">Join !</a>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="ml-4 mt-5">
  <!-- FLASH : error in case the user doesn't fill the form correctly -->
  <% if flash[:danger] %>
  <div class='alert alert-danger' role='alert'>
    <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
      <span class="close-button" aria-hidden='true'>&times</span>
    </button>
  </div>
  <% end %>
  <h1>Create a new event</h1>

  <%= form_tag url_for(action: 'create'), method: "post" do %>

       <%= label_tag 'Title' %><br/>
       <%= text_field_tag 'title'%>
       <br /> <br />

       <%= label_tag 'Description (minimum 20 caracters)' %><br/>
       <%= text_area_tag 'description'%>
       <br/> <br />

       <%= label_tag 'Start Date (yyyy-mm-dd hh:mm:ss)' %><br/>
       <%= text_area_tag 'start_date'%>
       <br/> <br />

       <%= label_tag 'Duration' %><br/>
       <%= text_area_tag 'duration'%>
       <br/> <br />

       <%= label_tag 'Location' %><br/>
       <%= text_area_tag 'location'%>
       <br/> <br />

       <%= label_tag 'Price' %><br/>
       <%= text_area_tag 'price'%>
       <br/> <br />

       <%= submit_tag "Create Post" %>
     <% end %>






  <!-- <form>
  <div class="form-group">
    <label for="exampleFormControlInput1">Email address</label>
    <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
  </div>
  <div class="form-group">
    <label for="exampleFormControlSelect1">Example select</label>
    <select class="form-control" id="exampleFormControlSelect1">
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5</option>
    </select>
  </div>
  <div class="form-group">
    <label for="exampleFormControlSelect2">Example multiple select</label>
    <select multiple class="form-control" id="exampleFormControlSelect2">
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5</option>
    </select>
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">Example textarea</label>
    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
  </div>
</form> -->

app/views/events/show.html.erb
<h1> Event n° <%= @event.id %> </h1>
<br>
<br>
<ul class="list-group list-group-flush">
  <li class="list-group-item">Event title : <em> <%=@event.title%>  </em></li>
  <li class="list-group-item">Last name :<em><%= @event.description %></em></li>
  <li class="list-group-item">Start date : <em><%= @event.start_date %></em> </li>
  <li class="list-group-item">Duration : <em><%= @event.duration %></em> </li>
  <li class="list-group-item">Location : <em><%= @event.location %></em></li>
  <li class="list-group-item">Price : <em><%= @event.price %>€</em></li>
  <li class="list-group-item">Participants : <em><%= @event.attendees.count %></em></li>
</ul>

<% if user_signed_in? && not_admin_nor_attending %>
<div class="container mt-4">
  <div class="text-center">
    <%= link_to "Join !", new_event_charge_path(@event.id), class: "btn btn-outline-success" %>

  </div>
  <% elsif current_user == @event.admin %>
  <div class="text-center">
    <%= link_to "See attendees", event_attendances_path(@event.id), class: "btn btn-outline-info" %>
  </div>

  <%end%>

app/views/events/update.html.erb
<h1>Event#update</h1>
<p>Find me in app/views/event/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eventbride</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="<%=root_path%>">
      <img src="http://www.brocerystore.com/wp-content/uploads/2015/09/bro_TMlogo_black.png" width="50" height="30" class="d-inline-block align-top" alt=""></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="<%=new_event_path%>">New Event <span class="sr-only">(current)</span></a>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li class="nav-item dropdown ml-auto">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Account
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="<%=user_path(current_user.id)%>">View Profile</a>
              <%= link_to "Sign out", destroy_user_session_path, class: 'dropdown-item', method: :delete %>
            </div>
          </li>
          <% else %>
          <li class="nav-item active ml-auto">
            <a class="nav-link" href="<%=new_user_session_path%>">Login</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="<%=new_user_registration_path%>">Sign up</a>
          </li>
          <% end %>
        </ul>
      </div>
    </nav>


    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
  </html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="m-4">

  <h1>Profil Page :</h1>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">First name : <em> <%=@user.first_name%>  </em></li>
    <li class="list-group-item">Last name :<em><%= @user.last_name %></em></li>
    <li class="list-group-item">Email : <em><%= @user.email %></em>  <%= link_to "(edit email & password)", edit_user_registration_path%> </li>
    <li class="list-group-item">Description : <em><%= @user.description %></em></li>
  </ul>
  <br>
  <br>

  <div class="row">
    <% @user.events.each do |event| %>
    <div class="col-sm-4 mb-2">
      <div class="list-group">
        <a href="<%=user_path(event.id)%>" class="list-group-item list-group-item-action">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">N°<%=event.id%> by <%= @user.first_name %></h5>
          </div>
          <p class="mb-1"><%= event.title %></p>
        </a>
      </div>
    </div>
    <% end %>
  </div>


</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>